export const tabsData = [
  {
    name: "Turbo Chargers",
    imgPath: "/hero-img.png",
    content: (
      <div key="tab1">
        <h3 className="text-3xl uppercase font-bold mb-4 lg:mb-6">Turbo Chargers</h3>
        <div className="flex flex-col gap-4 lg:gap-8">
          <p className="text-base">
            Turbochargers are devices used in internal combustion engines to
            increase power output by forcing more air into the combustion
            chamber. Here&apos;s how they work:
          </p>
          <ul className="list-disc list-inside">
            <li>Intake of Air</li>
            <li>Exhaust Gas Flow</li>
            <li>Turbine and Compressor</li>
            <li>Compression of Air</li>
          </ul>
        </div>
      </div>
    ),
  },
  {
    name: "Wastegates",
    imgPath: "/hero-img.png",
    content: (
      <div key="tab2">
        <h3 className="text-3xl uppercase font-bold mb-4 lg:mb-6">Wastegates</h3>
        <div className="flex flex-col gap-4 lg:gap-8">
          <p className="text-base">
            Wastegates are critical components in turbocharged engines that
            regulate the amount of exhaust gases flowing into the turbine of the
            turbocharger.
          </p>
          <ul className="list-disc list-inside">
            <li>Exhaust Gas Flow Control</li>
            <li>Boost Pressure Regulation</li>
            <li>Preventing Overboost</li>
            <li>Actuation Mechanisms</li>
          </ul>
        </div>
      </div>
    ),
  },
  {
    name: "Blow Off Valves",
    imgPath: "/hero-img.png",
    content: (
      <div key="tab3">
        <h3 className="text-3xl uppercase font-bold mb-4 lg:mb-6">Blow Off Valves</h3>
        <div className="flex flex-col gap-4 lg:gap-8">
          <p className="text-base">
            Blow-off valves are vital components in turbocharged engines,
            designed to release excess boost pressure when the throttle suddenly
            closes, preventing damage to the turbocharger and maintaining engine
            reliability. By diverting the pressurized air back into the intake
            system instead of forcing it back through the turbocharger, blow-off
            valves reduce stress on the turbo bearings and compressor wheel,
            prolonging their lifespan. This ensures consistent engine
            performance and protects against potentially costly repairs, making
            blow-off valves essential for the longevity and efficiency of
            turbocharged vehicles.
          </p>
        </div>
      </div>
    ),
  },
  {
    name: "Clamp Hoses",
    imgPath: "/hero-img.png",
    content: (
      <div key="tab4">
        <h3 className="text-3xl uppercase font-bold mb-4 lg:mb-6">Clamp Hoses</h3>
        <div className="flex flex-col gap-4 lg:gap-8">
          <p className="text-base">
            Clamp hoses for turbo applications are specifically designed to
            withstand the high temperatures and pressures associated with
            turbocharged engines. These hoses are often made from heat-resistant
            materials such as silicone or reinforced rubber, which can withstand
            the intense heat generated by the turbocharger. In turbocharger
            systems, clamp hoses are used to connect various components such as
            the turbocharger itself, intercooler, intake manifold, and
            wastegate. These hoses must be able to handle the significant boost
            pressures generated by the turbocharger without leaking or
            collapsing.
          </p>
        </div>
      </div>
    ),
  },
];
